# Generated by Django 5.0.1 on 2024-01-18 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Специальные предложения'), (2, 'Акция')], verbose_name='Тип')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(help_text='Успей купить!', max_length=150, verbose_name='Название')),
                ('datefrom', models.DateField(verbose_name='Дата начала акции')),
                ('dateto', models.DateField(verbose_name='Дата окончания акции')),
                ('date', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('img', models.ImageField(upload_to='promotions/%Y_%m', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки (Акция/Предложения)',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('img', models.ImageField(upload_to='story_images', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, help_text='Если есть', max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='StoryVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='stories', verbose_name='История')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='histori.stories')),
            ],
            options={
                'verbose_name': 'Истории',
                'verbose_name_plural': 'История',
            },
        ),
    ]
