# Generated by Django 5.0.1 on 2024-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_request',
            field=models.BooleanField(default=False),
        ),
    ]
